language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script: 
  - mkdocs build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ];then mkdocs gh-deploy --force --clean; fi'

branches:
  only:
    - master
